name: Deploy to Firebase Functions on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        working-directory: ./packages/api
        run: |
          yarn workspace api install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project=default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
